version: '3.7'

services:
  micro-crm-apache:
    container_name: micro-crm-apache
    build: ./services/server-alpine3.9.3-apache2.4.39-php7.3.4
    volumes:
    - $PWD:/var/www/localhost/htdocs
    - $PWD/services/server-alpine3.9.3-apache2.4.39-php7.3.4/etc/php/7.3/php.ini:/etc/php/7.3/php.ini
    - $PWD/services/server-alpine3.9.3-apache2.4.39-php7.3.4/etc/apache2/httpd.conf:/etc/apache2/httpd.conf
    ports:
    - "127.0.0.1:80:80"
    links:
    - "micro-crm-mariadb"

  micro-crm-nginx:
    container_name: micro-crm-nginx
    build: ./services/server-alpine3.9.3-nginx1.14.2-php7.3.4
    volumes:
      - $PWD:/var/www/html
      - $PWD/services/server-alpine3.9.3-nginx1.14.2-php7.3.4/etc/php/7.3/php.ini:/etc/php/7.3/php.ini
      - $PWD/services/server-alpine3.9.3-nginx1.14.2-php7.3.4/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/services/server-alpine3.9.3-nginx1.14.2-php7.3.4/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "127.0.0.2:80:80"
    links:
      - "micro-crm-mariadb"

  micro-crm-mariadb:
    container_name: micro-crm-mariadb
    image: bianjp/mariadb-alpine:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - $PWD/services/db-alpine3.9.3-mariadb10.3.13/data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"